<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="EPPlus" Version="7.5.2" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.12.1" />
    <PackageReference Include="MimeKit" Version="4.14.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Razorpay" Version="3.3.2" />
    <PackageReference Include="Selenium.WebDriver" Version="4.20.0" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="131.0.6778.20400" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.1" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Portable.BouncyCastle" Version="1.9.0" ExcludeAssets="all" />
	</ItemGroup>

  <ItemGroup>
    
    <ProjectReference Include="..\InstantPay.Infrastructure\InstantPay.Infrastructure.csproj" />
    
    <ProjectReference Include="..\InstantPay.SharedKernel\InstantPay.SharedKernel.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
